// Generated by CoffeeScript 1.6.2
(function() {
  describe('deck', function() {
    var deck, hand;

    deck = null;
    hand = null;
    beforeEach(function() {
      return deck = new Deck();
    });
    describe('hit', function() {
      beforeEach(function() {
        return hand = deck.dealPlayer();
      });
      return it('should give the last card from the deck', function() {
        expect(deck.length).toBe(50);
        expect(deck.last()).toEqual(hand.hit());
        expect(deck.length).toBe(49);
        expect(deck.last()).toEqual(hand.hit());
        return expect(deck.length).toBe(48);
      });
    });
    return describe('card counts in shoes', function() {
      it('should have 52 cards in 1 deck shoe', function() {
        return expect(deck.length).toBe(52);
      });
      return it('should have 52 cards for each deck in shoe', function() {
        deck = new Deck();
        deck.addMoreDecks(1);
        expect(deck.length).toBe(104);
        deck = new Deck;
        deck.addMoreDecks(9);
        return expect(deck.length).toBe(520);
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=DeckSpec.map
*/
